name: sicdesign
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23777
title: '[sic]design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000011'
    - '#000000'
    - '#00001c'
    - '#000008'
    - '#000008'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
